<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "rkw_alerts"
 *
 * Auto generated by Extension Builder 2015-08-12
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
	'title' => 'RKW Alerts',
	'description' => 'Extension for sending news-alerts',
	'category' => 'plugin',
	'author' => 'Steffen Kroggel',
	'author_email' => 'developer@steffenkroggel.de',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '9.5.0',
	'constraints' => [
		'depends' => [
			'typo3' => '9.5.0-9.5.99',
            'core_extended' => '9.5.4-9.5.99',
            'ajax_api' => '9.5.0-9.5.99',
            'rkw_mailer' => '8.7.55-8.7.99',
			'rkw_registration' => '8.7.0-8.7.99',
			'rkw_projects' => '8.7.0-8.7.99',
            'sr_freecap' => '2.5.0-2.5.99'
		],
		'conflicts' => [
		],
		'suggests' => [
		],
	],
];
